version: '2.3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8888 --noreload
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    restart: always    
    mem_limit: 250m