# Generated by Django 2.1.7 on 2019-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myDashboard', '0001_initial'),
        ('myDashboard', '0002_unilinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dash_apps',
            name='Type',
            field= models.TextField()
        ),
    ]
