# Generated by Django 2.1.7 on 2019-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myDashboard', '0005_ipLog'),
    ]

    operations = [
        migrations.AlterField(
            model_name="ip_log",
            name='time',
            field = models.DateTimeField(),
        ),
    ]
