# Generated by Django 2.1.7 on 2019-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myDashboard', '0005_ipLog_corr'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_sites_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('time', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        )
    ]
