# Generated by Django 2.1.7 on 2019-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myDashboard', '0008_jobs_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs_rating",
            name='job_id',
            field = models.TextField(),
        ),
    ]
